name: Validation

on:
  push:
    branches:
      - 'master'
  pull_request:
permissions:
  contents: read

jobs:
  test:
    name: Validation
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout Project Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: Install dependencies and build
        run: npm ci
      - name: Build TypeScript
        run: npm run build
      - name: Check TypeScript
        run: npm run typecheck
      - name: Test
        run: npm test
